import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'

/** Convert plain text lines to HTML paragraphs */
function p(...lines: string[]): string {
  return lines.map(l => `<p>${l.trim()}</p>`).join('')
}

const CHAPTERS = [
  {
    number: 1,
    title: 'The Drowned Woman',
    content: p(
      'The first men who saw the woman thought she was silk from a merchant ship.',
      'They saw the silk was moving against the current like a fish reflecting the morning sun. When they pulled their nets closer and the dawn light broke fully across the water, they saw it was a drowned woman, and she was more beautiful than any woman they had ever seen.',
      'She was naked, floating face-up in the water, long black hair spread around her like ink. Her skin was pale, and her lips were red as if she had just eaten pomegranate seeds.',
      'The fishermen, who were from the small village of Shíyú, muttered prayers to Buddha. She was heavy, heavier than any woman should be, as if her bones were made of reef. It took three men to lift her into the boat, and even then, the vessel sat lower in the water than it should have.',
      'When they laid her on the deck, they noticed her skin was cold — cold of places where sunlight never reached.',
      '"Throw it back in," said Old Hu, who had fished these waters for forty years. His hands were scarred from a lifetime of rope and net, and his left eye was clouded white from an infection he\'d gotten two decades ago. "No good ever comes from things found free."',
      'The youngest among them, a boy named Jang, who had been betrothed just two months ago, had already wrapped the drowned woman in his cotton jacket.',
      'There were five of them in the boat. Ship-owner Old Hu, and his apprentices: Jang, the Hu Brothers who were always arguing about whose turn it was to mend the nets, and Tortoise, who was a simple-minded young lad that could haul nets that would break another man\'s back.',
      'Jang had been promised in marriage in the spring to Miss Wang. Wang the rice merchant had four daughters and needed to settle them, and Old Hu owned two boats and a good stretch of drying racks. The betrothal had been finalized, the bride price paid.',
      '"Even in death something can be so beautiful," said the younger Hu brother, his monkey-like face split in a grin that showed too many teeth. His usual witty composure had cracked, replaced by hunger. He couldn\'t stop staring, his eyes tracing the curve of her neck, the perfect symmetry of her face, the way her wet hair clung to her pale shoulders like calligraphy on silk.',
      '"She\'s not dead," muttered the older Hu brother to himself, whose own wife had run off with a salt merchant three years ago, leaving him with two children and a bitterness.',
      'Tortoise\'s simple face froze in astonishment. He had not been with a woman, barely seen a woman\'s skin before. He reached out one thick finger to touch her, then pulled back.',
      'Jang\'s eyes were fixed on her face—that impossible face that seemed to shift slightly in the changing light, revealing new angles of perfection with each passing moment. Her lips were parted just slightly, and even unconscious there was something about her expression that suggested secrets, mysteries, promises of things no village woman could ever offer.',
      '"Out of courtesy," the older Hu brother cleared his throat, forced his eyes away, "To the town?"',
      'Old Hu didn\'t make a sound at first. The old man had seen everything the sea could offer—storms that swallowed boats whole, fish that glowed in the dark—stood transfixed.',
      'He couldn\'t quite move his eyes away from the shocking whiteness of the woman\'s skin, luminous as pearl, as if emitting its own light in the grey dawn. Her other-worldly features on that youthful face held him captive—high cheekbones that could cut glass, a nose so perfectly formed, eyes that even closed seemed to contain depths no man could fathom. Not a single sign of aging, not a blemish, not even a freckle marred that pretty thing.',
      '"Bossman?" the younger Hu brother pressed. "What you say?"',
      'The old fisherman\'s weathered hand tightened on the rail of the boat. For a moment, something flickered across his scarred face. His mouth opened, then closed. His fingers drummed once against the wood.',
      '"Aye," he said finally, his voice rough as stone.',
      'When they brought the woman from shore to town, half the village was already waiting. News traveled fast in Shíyú—there were only sixty families, clustered in houses built from wood weathered grey by salt wind, with roofs of curved tile that had been fired in the kilns two villages over.',
      'The houses were small and efficient, built close together for warmth in winter, with narrow spaces between them where children played and dogs scavenged. The main street, if you could call it that, was packed dirt that turned to mud when it rained, lined with the few businesses that kept the village alive: Wang\'s rice shop, Qian\'s net-repair workshop, Old Widow Zhou\'s medicine stall, and the teahouse run by the three Hu sisters.',
      'The women came out first, wiping their hands on aprons, leaving behind morning rice half-cooked and laundry half-scrubbed. Old Hu\'s wife Auntie Hu, who had delivered every baby in the village for the past thirty years, pushed through the crowd. She was a broad woman with arms like tree trunks and a face that had seen too much to be surprised by anything.',
      'She examined the drowned woman on the beach, touching her wrist, pulling back an eyelid, placing her ear against the woman\'s gut. The crowd pressed closer—housewives and grandmothers, young girls who should have been helping their mothers, the village children who were supposed to be collecting firewood but had abandoned their baskets to see what the excitement was about. Even the Lu family\'s grandfather, who was eighty-three and hadn\'t left his bed in two years, had been carried out by his grandsons so he could witness the spectacle.',
      '"Not quite dead," Auntie Hu announced finally, straightening up with a grunt, "Not quite alive either. Her pulse is slow as winter tide. Skin\'s wrong too—feels like the inside of an oyster shell."',
      '"So will she live?" asked Little Mei, the youngest of the Hu sisters, who was braver than her older siblings and had pushed to the front of the crowd.',
      '"Water demon," said the Elder Lu, who had pushed through the crowd with his walking stick, his grandson Tu Tu supporting his other elbow. Elder Lu was the only one who could read texts. He had spent two years studying in Mingzhou proper when he was young, before his father died and he had to return to take over the family fishing boat. He still kept his books in a locked chest, and sometimes the village would pay him in fish to read auspicious dates for weddings or to interpret particularly vivid dreams. "There are such creatures in the Collected Tales of Mountains and Seas. Come from the deep."',
      '"Demon?" scoffed Wang the Rice Merchant. He wore a silk jacket even on ordinary days. His hands were soft. "Superstition. It\'s but a prostitute thrown overboard. Perhaps a concubine that displeased her man. It happens all the time in the big cities. When I was younger, I was living it up in..."',
      'Before he could finish, Jang, just eighteen years of age, had already lifted her in his arms. She was still heavy, impossibly heavy, but he carried her.',
      '"Taking her to the temple," Jang announced. "The Buddha saves lives."',
      'His betrothed, Miss Wang was at the back of the crowd. Her face was pretty in an ordinary way, with the typical round cheeks and small features of merchant-class daughters.',
      '"Dried Fish," she said, her voice carrying clearly over the crowd. "Put that thing down and come home. I need you to move the water barrels."',
      '"Later," he said, not looking at her.',
      'Miss Wang\'s face went very still.',
      'Jang carried the woman to the temple, which sat on a small hill overlooking the harbor. It was a modest structure, but well-maintained, with fresh incense burning daily and red banners that were replaced only every New Year.',
      'Jang laid the woman before the statue of Buddha, carved from camphor wood and painted in fading colors, which looked down at the scene with his traditional serene expression. Jang kowtowed three times, pressing his forehead to the stone floor until it hurt, and pleaded to the Buddha.',
      'The women brought food. The men brought curiosity to see something truly beautiful for once. The children tried to sneak in to see the drowned woman, and the old monk of the temple spent most of his time shooing them away while muttering prayers under his breath.',
      'Old Hu came in the evening after dinner and sat beside Jang.',
      '"Need you on the boat, boy." the old man said.',
      '"Aye."',
      '"What you doing?" Old Hu\'s voice was gentle, almost paternal, but there was steel underneath.',
      '"Taking a bet."',
      'Old Hu let out a long breath through his nose. He shifted his weight, his old bones creaking, and looked down at the drowned woman on the floor. Her chest was rising and falling now, and even in the dim light her skin seemed to glow faintly, like phosphorescence in deep water. "Good lad, you were. Fast learner. Had the hands for it."',
      'Old Hu placed one hand on the boy\'s shoulder. Those hands were scarred over from decades of sunburn and net-wielding, the skin thick as leather, the knuckles swollen with old breaks that had healed crooked. The hand was heavy.',
      '"I was your age," his good eye grew distant, looking at something only he could see. "I didn\'t read, but the other boys told me, out there in the Eastern sea, lies an island of folks with bearded faces who like to eat fishes raw. There, a capital on the sea, a capital like Hangzhou, but even bigger. There, the Emperor\'s tongue was still used. There, men from the continent—men like me—could still make an honest, good living."',
      'He paused, hand trembling slightly on Jang\'s shoulder, whether from age or emotion the boy couldn\'t tell. "I wanted to sail... never come back. I went down to the docks every morning to look at the ships."',
      '"Days turn into weeks, weeks turn into years. There was always something. My father got sick, needed me on the boat. Then he died, and the boat was mine, and then the debts were mine. Then came a girl—your age. I was, maybe younger—and she looked at me like I was worth something. Then came the wedding, kids, more mouths, thus more fishing."',
      'The boy looked up at the old man.',
      'Old Hu was like a father to him. His own dad disappeared on a stormy night along with his small fishing boat on the open sea.',
      'Jang had been six when it happened. Old Hu found the boy on the beach the next morning, staring at the empty horizon. The old man had said nothing, just sat beside him until the sun went down. Then he took the boy home, taught him things, raised him up in the trade.',
      '"I never sailed," Old Hu said. "So I don\'t know. Maybe you\'ll."',
    ),
  },
  {
    number: 2,
    title: 'The Rice Ball',
    content: p(
      'On the second day, the boy\'s betrothed came.',
      'Miss Wang was carrying a bundle—clothes, shoes. She set it down beside him.',
      '"I\'m going back," she said quietly, "to daddy."',
      'Jang looked up at her: "Once she wakes, I\'ll come back."',
      'Then they embraced. Next to him, she felt like a little girl, though she was only a year younger than him.',
      'The boy held his betrothed tightly, and for a moment he buried his face in her hair. It smelled like the rice shop—like grain and wood smoke and the jasmine oil her mother made her wear on special occasions.',
      'Miss Wang\'s hands came up to rest against his back, and he could feel the calluses on her palms. Her fingers found the familiar spot between his shoulder blades where he always got tense after a long day on the boat, and she pressed there gently, the way she\'d done many times. It was a small gesture. It spoke of something.',
      '"Eat," she said softly. "You\'re thin."',
      '"Always thin," he said.',
      '"Thinner than usual, then. Dried Fish is getting drier."',
      'Old joke between them, stupid joke.',
      'They pulled apart slightly, and Miss Wang reached up to brush something from his cheek. Her hand lingered there for a moment. She had nice hands, he\'d always thought. Capable hands. Hands that could make fish soup and fried shrimp and blood clam with soy sauce. Hands that would have touched him every day for the rest of their lives, in a thousand small, unremarkable ways.',
      '"Brought you something," Miss Wang reached into her sleeve. She pulled out a small bundle wrapped in cloth. Inside was a rice ball, still warm, wrapped around a piece of salted eel.',
      'She unwrapped it and held it up to his mouth, and without thinking, Jang took a bite. It was just as he remembered it.',
      '"I was thinking," she said, still holding the rice ball, feeding him another bite when he\'d swallowed the first, "about the house. The one you were building for us. I went by yesterday. The frame is good. Strong. You did good work on it."',
      'She paused, then continued more quietly. "I was going to plant jasmine outside the door. My mother said it brings good fortune to a marriage. The vines would grow up the posts, and in summer, the whole house would smell sweet."',
      'Jang was quiet.',
      '"And I was thinking we could ask Widow Zhou about her chickens. She has too many, and she said she\'d give us six hens and a rooster for some rice. We could build a coop in the back. Fresh eggs in the mornings." She continued.',
      'After he finished eating, she left.',
      'He stayed still.',
    ),
  },
  {
    number: 3,
    title: 'Moon of the Sea',
    content: p(
      'On the third morning, the drowned woman sat up.',
      'Her black hair cascading down her back like a waterfall of ink.',
      'The first thing she did was to look at the boy for a long while. And in that look, something reached inside him and touched places he\'d never known existed.',
      '"Wow," she said, not quite the proper tone of the city, but the tone common among the fishermen of these shores.',
      '"Your name?" he asked.',
      'She paused, tilting her head slightly. It was as if she was remembering something from very long ago. "Hai Yue. Moon of the Sea."',
      'When her gaze met his again, one corner of her mouth quirked up in amusement.',
      '"Which ship did you fall from? During a storm?" Jang asked. His hand had somehow found hers. Her hand was smaller than his, delicate, but the skin had that strange texture—smooth, cool, slippery.',
      '"I did not fall. I came on purpose. It was time."',
      '"Time?"',
      'She didn\'t say anything, allowing the boy\'s hand to be there.',
      '"Where are you from?" The boy added.',
      '"Down there," she said. Her voice dropped lower, more intimate. "A village there, just like yours, but built from the ribs of whales and roofed with turtle shells. The walls are lined with pearls, and the gardens are kelp forests where fish fly like birds."',
      'As she spoke, Jang imagined it.',
      'She moved closer still, until her forehead rested against his, until they were breathing the same air.',
      '"They are going to kill you." The boy lied.',
      '"Kill?" The girl asked.',
      '"Right. You are not of this world."',
      '"What do you reckon that we do, boy?"',
      '"We have to go before the others know you are awake."',
      '"But just who would we be running away from?" She asked.',
      'But the boy did not say.',
      'They fled through the village, the boy and the drowned woman, as people were just beginning to wake, past the half-finished house he was building for his wedding, past the boats and drying racks that smelled of fish and salt and his entire childhood.',
      'They sneaked past Wang\'s shop, where smoke was just beginning to rise from the cooking fire, where Miss Wang was helping her mother prepare eggs.',
      'They ran until they reached the forest path that led into the mountains.',
      'The boy knew these trails—he and his childhood friends had explored every inch of this coast, finding secret coves and hidden beaches, places where adults never went.',
      'There was one place in particular, a small valley where a freshwater stream tumbled down from the mountains to meet the sea, creating a sheltered cove surrounded by steep cliffs.',
      'It took them a day to reach it, walking through dense forest, climbing over rocks, following half-remembered paths. Hai Yue moved with grace over the rough terrain, never complaining. She looked at the boy with a look of admiration. Or so it was what appeared to him.',
      'When they finally reached the valley, Jang felt a surge of triumph.',
      'It was exactly as he remembered—a small crescent of sandy beach, a clear stream, trees heavy with fruit, and the constant music of waves. The cliffs on three sides meant no one could approach except by sea or by the difficult mountain path they had just traveled.',
      '"Home." he said.',
      'Hai Yue stepped forward onto the sand, her bare feet leaving shallow impressions that the waves immediately began to erase.',
      'She looked around slowly with the curiosity of a little girl, taking in the crescent beach, the waterfall tumbling down the cliff, the dense forest climbing the mountainside, the three surrounding cliffs that made the cove feel like a cupped hand.',
      'Her mouth softened, and she breathed in deeply, tasting the air—salt and pine and the mineral-rich stream mixed with seawater.',
      'Jang, too, felt something expand in his chest, a warmth that had nothing to do with the sun.',
      '"We can be happy here," Jang exclaimed. "Help me find good bamboo for the frame. I will build us a palace."',
      'Hai Yue laughed, a sound of waves hitting on rocks.',
    ),
  },
  {
    number: 4,
    title: 'A Palace',
    content: p(
      'Jang threw himself into building their home with a drive he had never felt.',
      'He cut bamboo from the thick groves that grew along the stream, selecting each stalk with care—not too young and green, not too old and brittle, aged to that perfect golden color. He cut young trees from the forest edge, saplings with straight trunks that he could strip and shape into support beams. With vines and split bamboo, he wove them into walls.',
      'It took him days just to finish the walls, bit by bit, working until his hands were raw, until his shoulders ached so badly he could barely lift his arms.',
      'But he didn\'t stop, didn\'t rest.',
      'At night, they would lie together on the pile of dry grass, and Hai Yue would listen as Jang talked. His disappointments, past, dreams, feelings. She listened like a little girl curious and fascinated by any words he muttered.',
      'Two weeks passed. The boy planted a garden in the rich black soil near the stream, virgin earth that yielded sweet potatoes and bok choy and long beans.',
      'He had learned this from Auntie Hu. He built bamboo irrigation channels, splitting the hollow stalks lengthwise and fitting them together, creating a network of waterways that sang with the constant music of flowing water, carrying the stream\'s bounty to every corner of his garden.',
      'He would sometimes walk along them in the early morning, watching the water catch the sunlight, feeling the pride of a man who had shaped the land to his will.',
      'He fashioned fishing nets and caught fish from the cove. The place began to look like a real homestead, prosperous and self-sufficient.',
      'He built a storage shed for dried fish and vegetables, constructed a proper cooking area with a stone hearth and a chimney that drew the smoke up and away instead of filling the hut. He made furniture, even carved a washing basin from a fallen log, hollowing it out over the course of a week until it was smooth and watertight, perfect for holding fresh water from the stream.',
      'In the evenings, he would sit on the beach and play music on a flute he\'d carved from bamboo, or release simple melodies by blowing across seashells of different sizes. Hai Yue would dance for him on these evenings, and it was the most beautiful thing Jang had ever seen.',
      'She moved as if she had no bones, as if her body were made of water that could take any shape it pleased. Her arms flowed like seaweed in a current, her legs bent and turned in curious ways.',
      'She wore only that simple wrap of cloth around her body. And she never danced to the music exactly—rather, she danced around it, through it, as if she and the music were having a conversation, as if his flute was asking questions and her body was answering them.',
      'Sometimes she would move fast, spinning and leaping with a joy that seemed almost childlike. Other times, she would move so slowly it was hypnotic, each gesture taking long seconds to complete, her arms rising through the air like kelp rising through water, and Jang would forget to breathe, forget to play, just watching her with his mouth open and hands frozen on the flute.',
      'One evening, after he\'d stopped playing, Hai Yue walked over to him with an expression he\'d rarely seen on her face, extending a hand to him.',
      '"I don\'t know how..." He said.',
      'She pulled him to his feet before he could continue.',
      '"Don\'t think. Do."',
      'She began to sway, and Jang tried to follow. Clumsily, his feet tangled.',
      'She began to hum—a melody he\'d never heard before, wordless and haunting, rising and falling like the tide itself. And as she hummed, she guided him through movements like a conversation between their bodies.',
      'When he started to stiffen up again, overthinking, she would squeeze his hand gently. When he found the rhythm, she would spin slightly, adding complexity without breaking the flow.',
      'They danced until Jang forgot to be self-conscious.',
      'The moon rose higher, painting everything in silver.',
      'Other evenings, when the tide was right and the moon was bright, they would swim together naked. Hai Yue would lead him out past the breakers, into the calmer water where the moonlight turned everything silver and black.',
      'Sometimes she would duck under the surface and disappear, only to pop up behind him and splash water in his face, laughing at his startled expression.',
      'Or she would float on her back, her hair spreading around her like black silk on the water, and point out constellations, telling him their names in her language—words that sounded like waves and wind and things he had no reference for.',
      'They would race from one end of the cove to the other. She always won, but she would circle back to swim beside him, matching his pace, encouraging him when he got tired.',
      'Once, she taught him to float without moving, to just trust the salt water to hold him up, and they lay there side by side, bobbing gently with the swells, looking up at the stars in silence.',
      'Lying beside her on the sand, their bodies touching, the sea breeze cooling their skin, Jang felt a contentment he hadn\'t known was possible.',
      '"What are you thinking?" he asked softly.',
      'The moon was high, casting their intertwined shadows on the beach.',
      'Hai Yue was quiet for a long moment, staring up at the stars. When she spoke, her voice was different—smaller, more vulnerable than he\'d ever heard it. "About stopping."',
      'He didn\'t know what she meant.',
      'She buried her face in his neck, and he felt wetness on his skin.',
      '"Promise me," she whispered. "Promise me that when things get hard, when we change, you won\'t…"',
      'He held her tight into his skin.',
      'She was his first. Her body was soft, her hairless skin slippery like a fish. Her body bending and flowing, wrapping around him like water.',
      'Afterward, he would lie in her arms, his head resting on her chest, feeling her heartbeat, steady as waves.',
      'He would feel whole, as if all the missing pieces had suddenly clicked into place.',
      '"Tell me… your home," he would murmur against her skin. "The village beneath the sea."',
      'Hai Yue would be silent for a long moment, her fingers running through his hair in slow, soothing strokes.',
      '"Cold." she said finally, her voice barely above a whisper.',
      '"Got a family?"',
      'Her voice shook: "Nothing lasts."',
      'He just held her, and she held him.',
      'They lay together in the hut they built, listening to the waves and mosquitoes and the night birds and the sound of each other breathing.',
    ),
  },
  {
    number: 5,
    title: 'Every Morning',
    content: p(
      'He would wake every morning with her beside him.',
      'They\'d rise with the dawn. Jang checked the nets and tended the irrigation channels. Hai Yue started the fire, cooked rice.',
      'In the garden, they worked side by side—him pulling weeds, her harvesting. She had a sense for growing things.',
      'Midday, she\'d mend clothes and weave nets while he worked on the boat.',
      'Afternoons, he\'d cut bamboo or haul water while she smoked fish over the fire. Sometimes she\'d make soup in the pot—chopping ginger and wild herbs with careful precision, adding dried fish and whatever vegetables they\'d gathered, stirring slowly while the broth simmered and filled the hut with steam and fragrance.',
      'She learned fast—how to gut fish without wasting meat, how to predict rain by watching the birds, how long to boil bones to extract every bit of flavor for the broth.',
      'They took turns cooking.',
      'After dinner, he\'d carve tools while she wove baskets from beach grass.',
      'Before sleep, they\'d walk the perimeter together.',
      '"We built something today," he\'d say.',
      'Three weeks into their idyllic existence, on a night when the moon was full and huge, hanging over the ocean like a silver plate, Jang woke to a sound.',
      'At first he thought it was the waves. But something about the rhythm was wrong, too regular, too deliberate, like a heartbeat.',
      'Then he heard it again. A rhythmic pounding. Something striking the door of their hut, three slow beats, then silence, then three more beats, like something asking permission to enter.',
      'Jang sat up, his skin prickling with a cold that had nothing to do with the night air.',
      'Even the insects had stopped their chirping. The entire valley seemed to be holding its breath, waiting.',
      'Beside him, Hai Yue was awake too, her eyes reflecting the moonlight streaming through the cracks in the bamboo walls, but there was something different in her expression—a kind of alertness, like an animal that has caught a familiar scent on the wind.',
      'She sat up, her head tilted slightly to one side, listening to something Jang couldn\'t hear, some frequency that existed below or above perception.',
      'He sat up: "You heard?"',
      'She nodded.',
      'The pounding came again, harder. The door shook on its bamboo hinges.',
      'Jang grabbed the chopping knife from the table and moved toward the door. "Anyone there?" he called out, deepening his voice.',
      'The only response was a strange noise, like a fish moving its cheeks.',
      'Jang looked back at Hai Yue.',
      'He opened the door.',
      'The creature standing in the moonlight was eight feet tall.',
      'It stood hunched and twisted. It had the basic shape of a man—two legs, two arms, a torso, a head—but that\'s where the resemblance ended.',
      'Its body was covered in grey-green scales, each one the size of Jang\'s palm, studded with barnacles that had grown in clusters across its shoulders and chest, some of them still alive and opening their tiny mouths to filter the air as if searching for water.',
      'Long strands of kelp trailed from its head and arms, dark brown and glistening with slime, moving slightly in the night breeze as if the creature carried its own small ocean with it.',
      'Its head was elongated, the skull stretched backward into an unnatural shape, more fish than man, with a mouth that split its face nearly to where human ears would be. When it opened that mouth, Jang could see rows of human teeth, layer upon layer of them like a shark\'s. Its hands were webbed between every finger.',
      'The creature\'s chest rose and fell with labored breathing. Its eyes—those were the worst part—its eyes were that of humans.',
      'Jang didn\'t think. Instinct took over. He lunged forward with the kitchen knife and drove it into the creature\'s chest, right where a human\'s heart would be.',
      'The blade sank deep, meeting resistance from the thick, scaled hide before punching through. Hot liquid, not quite blood, spurted over his hand.',
      'The creature staggered back, black blood pouring from the wound. It reached for Jang with its claws.',
      'Before it died, the fishman looked confused. As if it couldn\'t comprehend what just happened and why he did this.',
      'Jang pulled the knife out—it came with a wet sucking sound—and stabbed again, this time higher, near where the throat met the chest. And again, lower, feeling for organs he couldn\'t see.',
      'He had done this before. Fishermen gut fishes.',
      'Finally, the creature collapsed in the sand outside his hut.',
      'The smell was overwhelming—fish and rot, like fruit left too long in the sun.',
      'Jang stood there, gasping, covered in the creature\'s filth. His hands were shaking so badly he could barely hold the knife.',
      'He looked down at the body, really looked at it for the first time. In death, it seemed smaller, more pathetic.',
      'Hai Yue came out and looked at the body.',
      'She paused for a long moment, then sighed, turned to Jang. In an almost hopeless tone: "The sea..."',
      'She started shaking: "want me back."',
      'Jang felt cold dread settle in his stomach.',
      'From the back, he held her tight. Trying to remain in composure: "No one will take you from me."',
      'When they went back inside, Hai Yue washed away the fish blood from his skin in silence.',
      'Before the sun, Jang dragged the fish-man\'s body down the hill and put it back into the sea.',
      'He looked long and hard at the sea. There was no bird at sunrise. No waves.',
      'It was at this moment, standing in the pre-dawn darkness with dried blood on his hands, that Jang understood something fundamental had shifted.',
      'Things would never be the same again.',
    ),
  },
  {
    number: 6,
    title: 'The Full Moon',
    content: p(
      'The next full moon, Jang woke in the depths of night.',
      'The sound came from the eastern wall, where Jang had left a gap between the bamboo slats for ventilation—sea breezes through during hot afternoons, cooling their home.',
      'First came a single tentacle through the gap. It moved with horrible intelligence.',
      'Then came another tentacle, squeezing through the gap like water finding its way through stone.',
      'Through the gaps in the wall, he could see the creature\'s body—a massive, bulbous sack of flesh covered in pink-colored skin. And beneath that grotesque ball of a body were two human legs, pale and muscular with leg hair.',
      'The creature was trying to force its entire body through the wall, more tentacles were coming through now—six, eight, ten.',
      'Jang slashed at the nearest tentacle with the knife he always kept close, and the blade bit deep, releasing a spray of black ichor.',
      'The tentacle recoiled but didn\'t release him, and two more wrapped around his chest, beginning to squeeze. He could hear his ribs creaking, feel something starting to give way.',
      'He slashed again and again. His vision began to tunnel, and finally one of the tentacles around his neck loosened enough for him to draw a desperate breath.',
      'The fight lasted perhaps five minutes, though it felt like hours.',
      'The creature\'s bulbous body was wedged in the opening, too large to fit through but too committed to retreat, and Jang saw his opportunity. He drove the knife deep into the soft flesh of the body itself, right where the tentacles connected to the central mass, and twisted.',
      'The creature made a high-pitched curse, almost like a human sentence. Its body began to deflate like a bladder losing air and the human legs twitched once, twice, then went still.',
      'Jang gathered what remained of the creature—a few chunks of flesh with those hairy legs hanging behind—and carried them down to the water.',
      'He turned and saw Hai Yue standing on the beach. She was wearing the simple robe he had sewn for her from sailcloth.',
      '"You\'re hurt," she said when he reached the shore.',
      '"I\'ll live," Jang said, touching his throat where the suckers had left circular bruises, like a necklace of purple coins.',
      'They spent the next day repairing the wall, making the bamboo walls thicker, stronger.',
      'They were building a fortress now.',
    ),
  },
  {
    number: 7,
    title: 'The Boy in the Storm',
    content: p(
      'Two weeks later, a storm rolled in from the east.',
      'Jang had been checking his fishing nets on the beach when the first drops hit. They were huge, warm drops that exploded on impact, and within seconds the sky opened up completely. The rain came down so hard it felt like being beaten, and the wind picked up with terrifying speed, bending the trees nearly horizontal.',
      'On the sea, a small fishing boat, spinning in the massive waves like a toy. And clinging to the hull, barely visible through the sheets of rain and sea spray, was a small figure. A child.',
      'Jang knew that boat. He\'d seen it a hundred times in the village harbor.',
      'Jang ran into the water, diving under the first massive breaker. The ocean was chaos, pulling him in a dozen directions at once. He surfaced, gasping, and swam hard toward the distant figure.',
      'The waves were the kind that could break boats. He could see the boy more clearly now—a small boy with a round face and terrified eyes. His name was Tu Tu, the grandson of Elder Lu. Each time Jang thought he was making progress, a wave would push him sideways or back.',
      'A wave crashed over his head, driving Jang deep under the water. Then everything went dark.',
      'When consciousness returned, Jang realized something was pulling him through the water with incredible force.',
      'He caught a glimpse of Hai Yue beside him. She got Tu Tu. Got the boy\'s thin arm just as he was going under. She got them to the beach.',
      'Through the rain and his blurred vision, he could see Hai Yue kneeling over Tu Tu\'s small body, and the boy wasn\'t moving. He was completely still, his skin a terrible grey-blue color, his eyes rolled back, his mouth slack.',
      '"No," Jang gasped, crawling over on his hands and knees. "No, no, no—"',
      'They rolled Tu Tu onto his side, and Hai Yue struck him hard between the shoulder blades—once, twice, three times. Water dribbled from the boy\'s mouth.',
      'Together, they turned Tu Tu onto his back. Jang placed his hands on the small chest—so small, the ribs fragile as bird bones under his palms—and pressed. Counted.',
      'The rain kept falling. The storm kept raging.',
      'Water came up. Suddenly, violently, Tu Tu convulsed and vomited seawater all over himself, coughing and choking and gasping. His eyes flew open.',
      'Then the boy started crying.',
      '"You\'re safe," Hai Yue said immediately, gathering him into her arms. "You\'re safe now. You\'re safe."',
      'They brought Tu Tu to the hut. Hai Yue built up the fire immediately, stripping off Tu Tu\'s soaked clothes with the efficient tenderness of a mother, wrapping him in their warmest blanket.',
      'The storm lasted three days. The rain came in waves, sometimes lessening to a drizzle before returning with renewed fury.',
      'Hai Yue cooked for Tu Tu. She made congee, slow-cooked, perfect for his raw throat. She caught crabs and made soup. She even made little rice balls with pickled vegetables inside, shaping them with her hands, making them small enough for a child\'s mouth. She worked over the fire like she\'d been cooking her whole life.',
      'She cleaned his cuts. She checked them every morning and night, watching for infection, changing the bandages.',
      'Tu Tu would wake screaming, thrashing in the blankets in fever and delirium, and Hai Yue would gather him up, rock him like a baby, sing songs in that strange language of hers. She would hold him for hours until he fell back asleep. She told him stories during the day when he was restless and frightened of the storm outside. Stories about islands far in the eastern seas.',
      'One afternoon, when Tu Tu was napping, Jang found Hai Yue sitting by the fire, her hand resting on her barely-visible belly, staring at nothing.',
      '"You\'re good with him," Jang said softly.',
      'She smiled without looking at him.',
      '"You\'ll be a good mother," Jang said. "To our kid."',
      '"A mother\'s love..." Hai Yue\'s voice was thick with emotion. "It\'s different from any other love." She paused. "His mother needs to know he\'s alive."',
      'Jang reached the village just after midnight. He and Tu Tu made their way to the Lu family\'s house—a small one near the harbor with a fishing boat pulled up in the yard.',
      'Every light in the house was burning. Through the windows, Jang could see figures moving inside—people were awake, waiting.',
      '"Go," he said quietly.',
      'But Tu Tu didn\'t move. He stood there in the dark street, looking between Jang and the lit windows of his home.',
      '"I don\'t want to go back," Tu Tu said suddenly. "Can I stay with you? With you and auntie."',
      '"You\'re kind people," the boy continued. "My parents... they\'re always working, always worried about food, always tired. They don\'t... I wish they were like you. Warm like you. Free like you."',
      'Jang crouched down to Tu Tu\'s level, put his hands on the boy\'s shoulders.',
      '"Can I come to see you?"',
      '"One day," Jang said. "We are going to leave this place with our kid. Sail east, to places where anything is possible."',
      'Tu Tu\'s eyes went wide. "Really?"',
      '"When that day comes, we\'re gonna need a good hand on deck."',
      'Tu Tu went inside. Jang stepped back into the shadows just as the door opened and a woman\'s silhouette appeared against the light. There was a moment of stillness, and then she held him tight.',
      'Jang walked through the village instead of going straight back. It was past midnight. The streets were empty.',
      'Old Hu\'s house was dark. In the yard were the nets, half-repaired. Tomorrow they would be finished. The next day there would be more nets.',
      'The teahouse was closed. Through the window he could see the tables, clean and waiting.',
      'Wang\'s shop looked prosperous. New paint. The steps repaired.',
      'At the edge of the village was the house Jang had started. Someone had finished the frame he started. The roof was mostly done. The walls were going up. He touched the doorframe. Some of the bamboo was his. The rest belonged to another man.',
    ),
  },
  {
    number: 8,
    title: 'A Boat for Four',
    content: p(
      'Jang began building a boat.',
      'Not a fishing boat but something that could cross open water. Something for four people—Hai Yue, himself, their child and Tu Tu. He sketched in the sand with a stick, calculated dimensions, imagined the hull cutting through waves.',
      'He salvaged wood from the forest. Strong hardwoods that would resist rot. Lighter pines for the upper structure. He tested each piece for strength.',
      'He expanded the hut for the baby. He tore down one wall and rebuilt it three feet out. A small room for the nursery. He lined the walls with soft grass woven tight. He built a cradle from driftwood and palm fronds. It took five days to get the balance right so it would rock without tipping. He sanded every surface smooth.',
      'Hai Yue\'s belly grew large. In the evenings he would place his hand on it. He felt movements inside.',
      '"I\'ll teach you to fish," he said. "I\'ll show you how to read the water. How to cast a net. The secret paths in the mountains. Where the fruit grows. Where the springs are. We\'ll play music on the beach. You\'ll grow up free. You can become anything. The world is yours."',
      'Sometimes Hai Yue would watch him talk to her belly. She would say nothing. Her hand would rest on top of his.',
      'Every full moon a creature came from the sea.',
      'Sometimes they walked upright on two legs like men. Sometimes they were more fish than man, with elongated bodies that moved serpentine through the shallows. Some were huge and slow, lumbering from the water like moving hills, their skin thick as leather, like whales. It took many stab wounds to bring them down. Others were smaller but faster, darting and weaving with intelligence that was almost human. These made him think. Made him adapt.',
      'He killed them all.',
      'Month after month, as the full moon rose and the tide came in high and heavy, something would emerge from the depths.',
      'He developed tactics, turning their home into a fortress and a trap. He planted sharpened bamboo stakes in the sand around the hut, angled upward at forty-five degrees. He kept oil burning in clay lamps near the entrance, ready to be thrown and create walls of fire. He built a second exit in the back of the hut, hidden behind a woven mat, so that if something came through the front door he could circle around.',
      'He made weapons—not just the kitchen knife, but spears from bamboo, a club studded with sharp shells, even a crude bow and arrows, though he was a terrible shot and abandoned that approach after the third creature dodged his arrows with ease.',
      'His body grew harder, no longer skinny, more muscled from the constant fighting and the hard work of maintaining their homestead. His arms developed the kind of strength that came from survival, from splitting bamboo and hauling nets and driving a knife through scales.',
      'His hands were perpetually scarred, the palms thick with calluses, the knuckles often split and bleeding from punching scales and barnacled skin. His chest and back were a map of near-misses—white scars from claws that had almost gutted him, puckered marks from teeth that had almost found his throat, burn marks from the acidic blood of a creature that had been part jellyfish.',
      'He moved differently now. Always alert. Always ready. Even during the day when he worked in the garden or repaired the hut, part of his attention stayed on the ocean, watching for the disturbance in the water that meant something was coming. He slept lightly. The smallest sound woke him and his hand would reach for the knife before his mind registered what he\'d heard.',
      'Hai Yue would run her fingers along the new scars sometimes, tracing the lines of muscle that had not been there when they first arrived.',
      '"You\'re becoming something else," she said.',
    ),
  },
  {
    number: 9,
    title: 'The Village on the Ridge',
    content: p(
      'Five months into their life together, Jang went to wash his face in the stream and caught sight of his reflection in a still pool.',
      'The face that stared back at him was not his own. Or rather, it was his face, but changed. He stood there for a long time, staring at the stranger wearing his face.',
      'That afternoon, while Hai Yue slept in the hut, Jang walked away.',
      'He took the fast pathway through the mountains that he and the Hu brothers had found as boys. It cut the journey from a full day to three hours.',
      'He reached the ridge as the sun descended. He stood hidden among the rocks and pines and watched the village.',
      'The fishing boats were returning. Seven of them in a line perfected over generations. The nets came up heavy. The men\'s voices carried on the wind, talking about the catch, about whose net had the biggest fish, about whether Old Hu could really predict the tides by the ache in his left knee.',
      'Old Hu was there. Unmistakable by the way he moved. He was teaching Tortoise something, his hands shaping the air the way they always did. Tortoise listened with absolute attention. Jang felt something that might have been jealousy. Tortoise was learning the things Old Hu would have taught him.',
      'The Hu brothers were arguing. Their voices rose in mock anger over something trivial. But there was rhythm to it. Comfort. Two men who had spent every day of their lives together.',
      'On the beach children were playing the same games Jang had played. Racing along the waterline. Jumping the incoming waves. Building cities in the sand that the tide would destroy. Tu Tu\'s sister was trying to catch crabs with her bare hands. Her grandmother sat nearby watching.',
      'The village square was alive with the evening market. Piles of vegetables. Bok choy and long beans and bitter melon. The fat white radishes that Wang\'s wife made into pickles. Baskets of eggs and dried mushrooms. The tea seller with his portable stove. The Hu sisters served customers at their teahouse with efficient grace. Moving between tables like dancers. Never forgetting who ordered what.',
      'Little Mei was serving young men from the port. On her finger was a new ring that caught the golden hour light. When she laughed it was not the laugh of a girl—it was now that of a woman.',
      'Wang the Rice Merchant was in front of his shop as he always was at this hour. Watching the market. Fresh paint on the sign. The quality of the rice displayed in neat pyramids. Wang\'s wife was beside him counting coins with the quick fingers of a woman who knew the value of every copper. Their nephew was sweeping the front of the shop with a bored expression.',
      'And then Jang saw her. Miss Wang. She emerged from the door above the rice shop.',
      'She was thinner than he remembered. The softness was gone. Replaced by the lean strength of a woman who worked. Her hair was pulled back in a simple style. No ornamentation. But she was smiling. Smiling as she talked to her father. Smiling as she adjusted her market basket. Smiling as Elder Shen\'s wife stopped her to ask about something.',
      'And Miss Wang\'s response was easy to read even from this distance. A shake of the head. A shrug. Jang\'s absence was just a fact now. Like the weather, the tides.',
      'Jang watched as she moved through the market. Stopping to examine vegetables. To chat with the Hu sisters. To help an elderly woman carry a basket of fish.',
      'The village went about its evening rituals with the precision of a well-rehearsed play. The old monk was sweeping the temple steps with methodical attention. Creating small clouds of dust that caught the golden light and floated for a moment before settling back to earth.',
      'Elder Lu sat outside his house. Smoking his long pipe and watching the world go by with detachment. Tu Tu was practicing calligraphy at a table beside him. His tongue poking out in concentration as he tried to make the characters match the model his grandfather had given him.',
      'Smoke rose from cooking fires all across the village. Jang could smell it even from this distance. The rice steaming. The fish frying in oil with ginger and scallions. The vegetables being stir-fried in well-seasoned woks. Someone was making soup. He could smell the richness of pork bones that had simmered all afternoon.',
      'The sounds of the village reached him in waves. Children\'s laughter and dogs barking and the steady thump-thump-thump of someone pounding laundry on rocks by the stream. The rhythmic scrape of tools being sharpened for tomorrow\'s work. And underneath it all the ever-present sound of the sea. Breathing in and out. In and out.',
      'Someone was singing. A woman\'s voice high and clear. One of the old work songs about mending nets or planting rice. One of those songs that had been sung for so many generations that no one remembered who had first started it.',
      'It was all so ordinary. So beautifully, achingly ordinary. And now watching it from outside Jang saw it for what it truly was. A tapestry. Each thread connected to every other thread. Each person part of a whole that was larger, older and more enduring than the individual.',
      'The sun was getting lower now. The village was preparing for night. Vendors packing up their unsold goods. Children being called home for dinner. The boats being secured. Lanterns were being lit, casting pools of warm light that would guide people home. The whole village was settling into itself. Tucking itself in for the night.',
      'Jang turned away. Every moment made the pain sharper.',
      'He ran back up the mountain path. Stumbling over roots and rocks. He made it back to the valley as the first stars appeared.',
      'Hai Yue was awake. Sitting by the fire. She looked up. Her eyes reflecting the flames.',
      '"Where\'d you go?" she asked. Her voice casual.',
      '"Fishing," Jang lied. "In the deep waters past the point."',
      '"Did you catch something?"',
      '"Nothing worth keeping."',
      'That night after Hai Yue fell asleep, Jang lay awake staring at the ceiling he had built.',
      'The knife was within reach. He had kept it sharp. It would be easy to drive it into her throat while she slept.',
      'He thought about becoming an apprentice somewhere far away. In a city where no one knew him. Learning an honest trade. Building a small life.',
      'He reached for the knife. His fingers closing around the handle. All he had to do was move his arm. Drive the blade down. And it would be over. He was good at this.',
      'But all he could do was lie awake in the darkness.',
      'The knife stayed in his hand until dawn. When Hai Yue stirred beside him he quickly put it away.',
    ),
  },
  {
    number: 10,
    title: 'East',
    content: p(
      'Sitting on the beach watching the tide come in, Jang found himself speaking without planning to.',
      '"After the baby," he said, "we leave." He glanced at her enormous belly, then back to the horizon.',
      'Hai Yue turned to him: "Where?"',
      '"Tell me about those islands again."',
      '"East, across the great ocean lies an island, many weeks sailing. They have built great cities of wood and paper, temples with curved roofs that point to the sky. The warriors there carry swords sharp enough to cut through bamboo stocks. They write in characters of the Continent too, yet speak it a different way. And in their city stood a mountain that breathes fire and snow at once." She said. "People of the rising sun, they call themselves. The water around their islands are rich, with so many fish it never runs out."',
      'Jang could picture it—the four of them arriving at those shores.',
      '"And beyond that?"',
      '"Further still," Hai Yue continued, "There are islands scattered across the ocean like stars across the sky. Some have people with dark skin and flowers in their hair, who build boats that can travel for months without touching land. They navigate by the stars and the waves, reading the ocean like your people read books. They have no winter, only endless summer, and the water is so warm and clear you can see fish swimming fifty feet below."',
      '"Ha." Jang said softly.',
      '"Something yet beyond that, something few from the old world have seen. Another continent, vast and strange. The people there have red skin and black hair. Cities of stone in mountains that touch the clouds. They have gold. So much gold they use it for decoration, for dishes, for ornaments. They would trade a cup of gold for a cup of grain and think nothing of it."',
      'She leaned closer, her voice dropping to a whisper as if sharing a great secret. "And if we travel far enough across that new continent, there is a narrow land—a strip of earth so thin you can walk from one ocean to another in just days. The people there say it\'s cursed, filled with jungle so thick the sun never reaches the ground, filled with jungle beasts and sickness. But on the other side..." Her eyes gleamed. "On the other side is another sea, a sea so large the land was tiny in comparison. Land where people have hair the color of straw or copper or even fire itself. And they smell. They smell of sourness, old meat and sweat, for they don\'t bathe. They think water is dangerous, that it opens the pores to disease, so they wear the same clothes for months until the fabric is stiff."',
      'Jang made a face.',
      'Hai Yue continued, warming to her description. "Don\'t let their strangeness fool you. Their kings and queens rule vast empires, commanding armies of men hiding in metal shells who ride great horses bred for war."',
      'Her voice grew more animated. "Their women paint their faces white as death and bind their bodies in tight cloth until they can barely breathe. Their men kneeling before the women to pledge devotion, warriors fighting each other to death for their favors."',
      '"Madness," Jang said, smiling.',
      '"It is mad. All the world is mad, once we leave to see it." She leaned her forehead against his. "And our child would grow up knowing no bounds. Our child would speak ten languages, taste food from a hundred kingdoms, swim in every ocean. Wouldn\'t that be something?"',
      'The vision seized him.',
      'They made love there on the beach as the sun set, her belly huge between them, the child moving inside her. Her hot skin against his warm flesh, the sound of waves, the boat parked in its home harbour.',
      'Afterward, they lay together on the sand, and Hai Yue spoke of more wonders: cities built on water, mountains that touched the sky, creatures he\'d never imagined.',
    ),
  },
  {
    number: 11,
    title: 'Blood Clams',
    content: p(
      'The things that came from the sea grew stronger and stranger.',
      'At six months, a massive thing emerged that had the body of a mantis shrimp—armored plates overlapping like roof tiles—the size of a large horse, with two enormous club-like appendages where its arms should have been. The creature moved with the clubs cocked and ready to strike with the force that could split open rocks.',
      'Jang had caught mantis shrimp before with Old Hu. So when the creature lunged at him, Jang watched for the telltale coiling of its segmented body and threw himself sideways. The clubs cratered the sand where he\'d been standing, the shockwave rattling through his feet.',
      'The creature was committed now, its clubs buried in sand, taking a moment to reset its spring-loaded appendages. Jang came around behind it—where its armor had gaps for movement—and drove his spear between the plates. Red blood sprayed.',
      'Jang stayed in its blind spot, stabbing into the gaps between armor. It was like fighting a puzzle. Finally, the creature collapsed.',
      'At seven months, they came in the grey light before dawn—not one or two creatures, but hundreds of them, emerging from the surf in a mass that made the beach look like it was alive and moving.',
      'Blood clams. Jang recognized them instantly, the same species fishermen harvested for food, with their dark red flesh and ridged shells. But these were wrong. They were too large, each one the size of both his fists together, and they moved with purpose that shellfish shouldn\'t possess, propelling themselves across the sand with horrifying speed.',
      'They came in a wave, hundreds of them, their shells clicking together like teeth chattering, leaving trails of red fluid in the sand. Jang had only under a minute to grab his spear before they reached him.',
      'The first ones attached to his ankles. He felt the shells clamp down, their ridged edges biting through his skin, and then came the pain—sharp as they began to feed. He kicked frantically, smashing several with his spear, but for every one he destroyed, three more took its place.',
      'They swarmed up his legs, dozens of them, their shells opening just enough to extend their soft bodies, latching onto his flesh with strength. Each one that attached began to chew, to rasp away at his skin with tongues covered in tiny teeth.',
      'Jang screamed and fell to his knees, trying to tear them off, but their grip was incredible. His fingers bled as he pried at their shells, and the moment he removed one, another would attach. They were climbing higher now, covering his thighs, reaching for his torso, each one a small mouth chewing, chewing, chewing.',
      'The pain was beyond anything he\'d experienced. A thousand small agonies spread across his body, each clam taking its tiny piece of him. He could feel his blood running down his legs, mixing with the red fluid the clams secreted.',
      'He crushed them with his hands, smashed them with rocks, stabbed them with his spear, but there were too many. They were pulling him down with their collective weight, and he couldn\'t get up, couldn\'t stand. His vision was starting to blur from blood loss.',
      'More clams reached his chest, his arms, his neck. One attached to his shoulder and he felt it begin its terrible work, scraping away skin, muscle, going deeper. He was going to die.',
      'Then she arrived.',
      'She had the cooking pot in her hands and she threw it across the mass of clams on Jang\'s lower body.',
      'The clams shrieked and released their grip. Hai Yue grabbed more pots, more boiling water, and poured it systematically over Jang\'s body, cooking the clams alive, making them release him one by one.',
      'She worked with terrible efficiency, tearing the remaining clams off him with her bare hands, not caring as the shells cut her palms, crushing them against rocks, throwing them back toward the ocean.',
      'Back in the hut, Jang collapsed. His entire body was covered in circular wounds where the clams had been.',
      'He was not going to make it this time.',
      'For three days, he had fever. Hai Yue brought him water and made him drink. She changed his bandages twice a day. The wounds on his legs were the worst. Red and swollen. She cleaned them with seawater that made him cry out.',
      'On the fourth day the fever broke. He could sit up. She fed him broth she\'d made from fish bones.',
      'By the second week he could stand. She helped him walk to the stream and back. His legs shook. The circular wounds were healing slowly.',
      '"You need to move," she said. "Or the muscles stiffen."',
      'She was right. Each day he walked a little farther. First just to the stream. Then to the garden. Then down to the beach. His legs ached but he kept walking.',
      'She made him eat. Fish and rice and vegetables from the garden. She said he needed strength. He was thinner now. The ribs showing through his skin. But the muscle was still there underneath.',
      'In the second week he tried to work. He checked the irrigation channels. Fixed a broken one. Weeded the garden for an hour before his legs gave out. Hai Yue found him sitting in the dirt.',
      '"Slow," she said.',
      'And then he cried.',
      'Each day he did more. By the third week he was back on the boat. Sanding. Fitting pieces. His hands still worked fine. It was just the legs that were weak.',
      'Hai Yue worked beside him those weeks. She did his share of the heavy work without complaint.',
      'One morning in the fourth week he woke and the pain was mostly gone. Just a dull ache when he walked. The scars were white now. He stood and walked to the stream without limping.',
      'Hai Yue was already up. Making breakfast. She looked at him and nodded.',
      '"Almost," she said.',
      'That day he went back to his full work. The garden and the nets and the boat. His legs held. By evening he was exhausted but it was the good exhaustion of work. Not the exhaustion of fighting his own body.',
      'That night they ate together by the fire. Her belly was much larger now, almost the size of a ripe watermelon, slightly pink and translucent. The child moving inside like breathing veins.',
      'The construction of the boat had progressed. He spent days selecting each piece, testing it for strength, rejecting anything with the slightest weakness. Every morning he would work on it, the frame slowly taking shape on the beach.',
      'Hai Yue would watch from the doorway of the hut, one hand on her swollen belly, and sometimes Jang would see something like sadness in her face.',
      '"When the baby comes," he would say, running his hand along the smooth curve of the hull, "We finish this. Seaworthy."',
      'Then he would continue sanding wood, lashing joints. When he worked on it, he could believe in the simple, tangible reality of wood and rope.',
      '"Almost," he said.',
    ),
  },
  {
    number: 12,
    title: 'Before',
    content: p(
      'Days before, the fish he caught had clouded eyes that seemed to track him even after death. The water itself felt thicker, more viscous.',
      'Hai Yue stared at the ocean for hours, unmoving. When he spoke to her, she didn\'t respond immediately, as if listening to something far away that he couldn\'t hear. Her belly moved as if something thick was sliding behind it.',
      'The water level was much higher now. He noticed.',
      'The night before they came, he dreamed. Long and senseless dreams where one ended and the other immediately began. He had been younger here, him and Tortoise, paddling out to a still water zone in the ocean with plenty of fish. Schools of fishes swam beneath the boys. The water was strangely still. In fact, the water did not move at all. Out of nowhere, a force—a force so strong and primal—pulled the boat whole down, down, more down, into the water. It filled his throat. He tried to swim. He tried everything. But nothing helped. The depth, the darkness awaited him openly.',
      'He woke to find Hai Yue cooking soup. She smiled. He didn\'t.',
      'Rain hammered the roof, and lightning split the sky every few seconds, turning night into day in violent flashes. Thunder shook the bamboo walls, and the wind howled like something alive and hungry.',
      '"It\'s time," she said, her voice barely audible over the storm.',
      'Jang had prepared for this. He had clean clothes, fresh water, and a sharp knife to cut the cord. He had made Hai Yue a soft bed of moss and palm fronds in the corner of the hut.',
      'Hai Yue\'s belly began to move, rippling like water, the skin stretching and contracting.',
      'Then it opened, opening like a mouth, revealing the interior.',
      'And from inside her, eggs emerged.',
      'One, two, few, then tens of eggs. They came out one after another, sliding from her body with wet, sucking sounds, each one the size of a melon, translucent and veined with purple lines that pulsed like blood vessels.',
      'Inside each egg, shadows moved—things with too many limbs, too many faces, too many fins.',
      'Hai Yue gathered them as they came, her hands cradling each one, placing them carefully around the fire pit. The eggs were warm to the touch, radiating heat, and they rocked slightly as the creatures inside shifted position. And they kept coming, kept sliding out of that opening in her belly.',
      'She moved among the eggs, touching each one, humming that wordless song, and the eggs responded, their movements becoming synchronized.',
      'Jang stood frozen, unable to speak.',
      'The torch was still shaking in his hand, casting wild shadows across the walls he had forged, the furniture he had crafted, the home he had built.',
      'Lightning flashed outside, illuminating the eggs in stark white light, and for a moment Jang could see the things inside them.',
      'Hai Yue finally looked at him, waiting, as if asking a question.',
      'He looked at Hai Yue, really looking at her for the first time. She was humming to them, touching each one with tenderness.',
      'Her smile looked ugly: "You\'re a good man, Jang."',
      'Then came the sound at the door. Three slow, deliberate knocks, audible over the storm.',
    ),
  },
  {
    number: 13,
    title: 'The Last Stand',
    content: p(
      '"Don\'t," she said quietly. Her hand reached to stop him, but stopped in mid air. She caught herself.',
      'Jang was already moving toward the door, knife in hand.',
      'He looked at her, his mouth open then closed, the words swallowed, then opened the door.',
      'Lightning illuminated the creature on the beach in stark detail.',
      'Massive, easily ten feet tall, with the thick, powerful body of a seal. Its skin was mottled grey and black, slick with rain and seawater. But where a seal\'s head should have been was a leathery face with man\'s eyes and seal\'s whiskers sprouting from the cheeks. In one of those terrible hands, it gripped a sword—a man-made sword.',
      'The creature\'s eyes fixed on Hai Yue standing in the doorway of the hut. When it spoke, its voice was deep and resonant: "Careful, Mom."',
      'Then, slowly the creature turned to look at Jang, and in the next flash of lightning, Jang saw its face clearly—it wore an expression of rage. Then darkness again, and the creature\'s roar—part bark, part human scream—cut through even the thunder.',
      'Jang pretended not to understand.',
      '"Stay inside." He smiled at Hai Yue. Gracefully, Jang bowed to her deeply. In the story she told him, this was how the men in steel armors in the strange continent did. And he walked into the storm, closing the door gently behind him.',
      'He breathed in the wetness in the air with a long, deep breath, letting rain wet his long hair.',
      'It was time. He opened his eyes.',
      'The rain was so heavy he could barely see. The beach had become a nightmare landscape of black sand and white foam, the ocean churning with violence. Lightning turned everything into a strobe—flash of light, darkness, flash of light, darkness—making the sight feel disconnected, like watching a series of horrifying paintings come to life.',
      'He charged forward towards the giant thing on the beach, drove his spear powerfully toward the creature\'s chest, but it moved with terrifying speed, rolling sideways and swinging its sword back at Jang.',
      'The blow caught Jang in the ribs, slicing superficially in his belly, lifting him off his feet and hurling him across the beach. Jang hit the sand hard, rain immediately filling his mouth and nose, the wind knocked out of him.',
      'The creature was on him before he could recover, appearing out of the darkness suddenly. Its weight was crushing, impossibly heavy, pressing him into the mud. Its claws raked across his shoulder, tearing through skin and muscle, and Jang screamed. The sound lost in thunder.',
      'Jang stabbed upward with the knife he kept in his belt, catching the thing in the throat just as the creature\'s ancient sword came down towards his chest.',
      'In one bold move, Jang knocked away the sword in the seal-man\'s hand and sliced into the beast\'s throat. The sword flew left a few meters onto the sand. Black blood sprayed, mixing with the rain, but the creature barely seemed to notice. It reared back and brought its flipper down on Jang\'s chest like a club, and Jang felt something crack.',
      'Lightning flashed, and in that moment Jang saw the creature\'s face inches from his own—the human eyes looking at him with hate. Then darkness, and teeth closing on his shoulder, tearing.',
      'Jang rolled away, gasping, got to his knees in the mud. The rain was washing his blood away as fast as it flowed, turning the beach into a soup of red and black. Jang spat blood on the sand.',
      'The creature circled him, visible only in lightning flashes—here, gone, there, gone—moving in unexpected ways.',
      'Jang quickly forced himself to his feet, swaying, blood running down his chest from the claw marks. Lightning showed him the creature charging, and this time Jang dove aside, bringing his spear across its flank as it passed. The spear bit deep, opening a long gash that poured more black blood onto the sand.',
      'The creature roared. It spun with impossible speed for something so large. Its flipper caught Jang across the face, and he felt his jaw crack, tasted blood mixing with rainwater, went down hard.',
      'Get up.',
      'He got to his hands and knees, spitting blood and rainwater. Lightning showed the creature towering over him, raising both flippers for a finishing blow, its face twisted in triumph.',
      'Jang lunged forward instead of back, driving his shoulder into the creature\'s bulk. They rolled across the sand, rain and blood and mud mixing. Jang stabbed wildly, hitting flesh and bone, and the creature\'s teeth found his arm, clamping down, grinding, eating.',
      'Jang screamed but didn\'t let go of the knife, kept stabbing in the darkness, guided by touch. When lightning flashed, he saw his own arm disappearing into the creature\'s mouth, saw his hand still gripping the knife buried in its side, saw black blood everywhere.',
      'Another blow sent him flying. He hit the ground and rolled, fetching up against something hard—the bamboo stakes.',
      'Jang got to his feet. Standing on his right leg, his left leg useless, torn. A big chunk of his right arm was missing. Blood poured from a dozen wounds, washed away by rain, replaced by fresh blood. The creature was bleeding too badly, its movements slowing.',
      'In the next flash of lightning, he saw it charging one more time, and Jang didn\'t try to dodge. In the darkness between flashes, he stepped forward to meet it on faith alone—the massive body bearing down on him. He felt its claws sink into his sides, felt teeth close on his shoulder, felt his own blood hot against his skin even in the cold rain.',
      'They hit the stakes together—he\'d judged the distance between two stakes—and the sharpened bamboo punched through the creature\'s body with a wet sound he felt through his own chest. Lightning revealed the creature\'s human eyes going wide with pain, impaled on multiple stakes, black blood pouring down the bamboo like oil.',
      'Jang heard it die. A long, rattling exhale that sounded too human, too sad.',
      'Jang collapsed beside it in the mud.',
      'He tried to get up. But he could only lie there in the mud, rain hammering his broken body.',
      'He heard footsteps approaching through the mud. Hai Yue\'s warm hand touched his face, and he managed to smile.',
      'She was carrying him through the storm, back toward the hut. Finally, he let his consciousness go.',
    ),
  },
  {
    number: 14,
    title: 'The Tub',
    content: p(
      'The heat hit him all at once.',
      'Jang\'s eyes flew open in agony. He was in the bathtub, the water already scalding his torn flesh, and Hai Yue was there, holding him down with hands that were impossibly strong.',
      'His mouth screamed more dying sounds, until boiling water filled his mouth. He tasted it. The soup base. Herbs, mushroom, bok choy.',
      'His hands gripped the edges of the tub and tried to pull himself up, muscles straining, but she pushed him back under. The scorching water closed over his face. His skin was already half-cooked, blistering.',
      'The pain was unlike anything he had ever experienced. Every nerve ending screaming simultaneously, his skin beginning to separate from muscle, muscle beginning to break down. He could feel his skin loosening, sloughing off in sheets.',
      'He thrashed wildly, desperately. His wounded leg kicked against the side of the tub. Whenever he surfaced, she\'d push him back under with firm hands.',
      '"Bye, Jang." She said while adding more vegetables to the tub.',
      'It had ended here. The thing he had held on for eighteen years.',
      'In the end, he saw his village. He saw his father teaching him to tie knots on a boat sunk a long time ago.',
      'Patient hands guiding his smaller ones. He must be, what, five years old then. The rope was thick and rough against his palms. His father\'s hands covered his own—weathered, scarred, warm.',
      '"Over, under, through," his father said.',
      'The rope moved through his father\'s fingers. The knot appeared, perfect, tight.',
      '"You."',
      'Jang tried. His small hands fumbled with the hemp. It tangled, came out wrong. He tried again. Wrong again. His palms hurt from the rough fiber.',
      'His father\'s hand covered his once more. "Again. Over, under, through."',
      'The hand guided him through the pattern. Over the standing end. Under the loop. Through the gap.',
      'Jang had never asked the sea for anything. Not for luck, not for calm water, not for safe return. Every morning before the light came, he came to the water\'s edge and stood there without asking.',
      'The rope slid against rope, hemp fibers catching and gripping. His father\'s callused fingers pressed his smaller ones into the right positions.',
    ),
  },
  {
    number: 15,
    title: 'The Water Demon',
    content: p(
      'The water demon, her face so beautiful you\'d pause a moment to just take in the sight. She stood over the tub, stirring occasionally with a long wooden paddle, keeping the meat from sticking to the bottom, maintaining the heat at just the right temperature.',
      'When the meat was cooked through, tender enough to pull apart easily, she began to feed her children. She used her hands to tear off pieces, dividing it equally among the mewling young, making sure even the smallest got their share. They ate with desperate hunger. She worked through the night, feeding them, humming that wordless song of the deep water.',
      'By dawn, the tub was empty except for bones.',
      'Hai Yue carried the leftover to the water. The bones were light. She waded out to her waist and let them go.',
      'She stood in the sea for a long time. It was a beautiful morning. The storm had passed. The sky was clear. The waves were gentle.',
      'Around her, the children swam in the cove. Testing their bodies. Learning. Some were more human. Some more fish.',
      'She wondered what he would have thought. Seeing them.',
      'He had become a true father.',
      'She walked to the hut. Inside, everything was as he had made it. The carved bowls. The sleeping mat. The cradle in the corner, sanded smooth. She touched the cradle\'s edge. She thought about the other woman. The one in the village.',
      'The waves rolled in. The waves rolled out.',
      'The sun climbed higher. The children called out to her in the water. She walked to the shore. The hut burned behind her, and the boat. The children swam in circles, waiting.',
      'Perhaps each man changed her. A little. In ways she could not name.',
      'She waded into the water. Turned back just once to look at the valley.',
      'The hut was fully engulfed now. Orange flames against blue sky.',
      'Soon there would be nothing left.',
    ),
  },
]

export async function GET() {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Not signed in. Sign in to the site first, then visit this URL.' }, { status: 401 })
  }

  // ── Step 1: find any existing novel by this user that looks like our novel ──
  let novelId: string | null = null

  // Try slug variants first
  for (const slug of ['the-boy-and-the-sea', 'the-boy-and-the-sea-1', 'boy-sea', 'boy-and-sea']) {
    const { data } = await supabase.from('novels').select('id').eq('slug', slug).maybeSingle()
    if (data) { novelId = (data as { id: string }).id; break }
  }

  // Try title match
  if (!novelId) {
    const { data } = await supabase
      .from('novels').select('id, title, slug')
      .ilike('title', '%boy%sea%').maybeSingle()
    if (data) novelId = (data as { id: string }).id
  }

  // Show all novels for debugging, then create fresh
  if (!novelId) {
    const { data: allNovels } = await supabase
      .from('novels').select('id, title, slug').eq('author_id', user.id).limit(20)

    // Create the novel from scratch
    const { data: created, error: createErr } = await supabase
      .from('novels')
      .insert({
        title: 'The Boy and the Sea',
        slug: 'the-boy-and-the-sea',
        author_id: user.id,
        status: 'complete',
        published_chapters: 0,
        tagline: 'Some loves are not meant to last.\nSome oceans never let go.',
        cover_bg: '#0a1525',
        cover_ink: '#e8e4dc',
        cover_accent: '#8fa3b1',
        cover_layout: 'banded',
      })
      .select('id')
      .maybeSingle()

    if (createErr || !created) {
      return NextResponse.json({
        error: 'Could not find or create novel.',
        createError: createErr?.message,
        yourNovels: allNovels,
        userId: user.id,
      }, { status: 500 })
    }
    novelId = (created as { id: string }).id
  }

  // ── Step 2: wipe existing chapters ──
  await supabase.from('chapters').delete().eq('novel_id', novelId)

  const now = new Date().toISOString()
  const errors: string[] = []

  for (const ch of CHAPTERS) {
    const wordCount = ch.content
      .replace(/<[^>]+>/g, ' ')
      .split(/\s+/)
      .filter(Boolean).length

    const { error } = await supabase.from('chapters').insert({
      novel_id: novelId,
      number: ch.number,
      title: ch.title,
      content: ch.content,
      word_count: wordCount,
      published_at: now,
      created_at: now,
      updated_at: now,
    })

    if (error) errors.push(`Ch ${ch.number}: ${error.message}`)
  }

  // ── Step 3: update novel metadata ──
  await supabase.from('novels').update({
    published_chapters: CHAPTERS.length,
    status: 'complete',
    updated_at: now,
  }).eq('id', novelId)

  if (errors.length) {
    return NextResponse.json({ ok: false, errors }, { status: 500 })
  }

  return NextResponse.json({
    ok: true,
    message: `All ${CHAPTERS.length} chapters seeded successfully.`,
    chapters: CHAPTERS.map(c => ({ number: c.number, title: c.title })),
  })
}
